// Generated by Cursor
// Routes for timeline pages
// Timeline data is now embedded in HTML templates and processed client-side

module.exports = (router) => {
  
  // GET: Search results timeline page
  router.get('/mvp/v6/timeline/search-results-timeline', (req, res) => {
    // Always prioritize query parameters - don't use session data for MRN/title
    const q = (req.query.q || '').trim();
    const mrnParam = (req.query.mrn || '').trim();
    const mrnFilterParam = (req.query.mrnFilter || '').trim();
    // Only use session as fallback if no query params provided
    const sessionTitle = (!q && !mrnParam && !mrnFilterParam) ? (req.session.data?.title || '').trim() : '';
    // Use query parameter first, then session fallback, then default
    const title = q || mrnParam || mrnFilterParam || sessionTitle || '25GBC64QCLFMUHPAR2';
    const eventType = req.query.eventType || req.session.data?.eventType || 'all';
    const sortBy = req.query.sortBy || req.session.data?.sortBy || 'descending';
    const mrnFilter = mrnFilterParam || title;
    
    req.session.data = req.session.data || {};
    // Always update session with current values to keep it in sync
    req.session.data.title = title;
    req.session.data.searchTerm = q || title;
    req.session.data.Cds = req.session.data.Cds || 'Customs declaration details';
    req.session.data.Ipaffs = req.session.data.Ipaffs || 'IPAFFS pre-notification (CHED) details';
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;
    req.session.data.mrnFilter = mrnFilter;

    // Sample list of MRNs (can be replaced with actual data source)
    const availableMrns = [title, '25GBC64QCLFMUHPAR2', '25GBC64QCLFMUHPAR3', '25GBC64QCLFMUHPAR4'];
    req.session.data.availableMrns = availableMrns;

    res.render('mvp/v6/timeline/search-results-timeline', {
      title,
      mrn: title,
      data: req.session.data
    });
  });

  // POST: Handle filter changes on search results page
  router.post('/mvp/v6/timeline/search-results-timeline', (req, res) => {
    const eventType = req.body.eventType || 'all';
    const sortBy = req.body.sortBy || 'descending';
    const mrnFilter = req.body.mrnFilter || req.query.mrnFilter || req.session.data?.title || '25GBC64QCLFMUHPAR2';
    const mrn = req.body.mrn || req.query.mrn || req.session.data?.title || '25GBC64QCLFMUHPAR2';

    req.session.data = req.session.data || {};
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;
    req.session.data.mrnFilter = mrnFilter;

    res.redirect(`/mvp/v6/timeline/search-results-timeline?q=${encodeURIComponent(mrnFilter)}&eventType=${eventType}&sortBy=${sortBy}&mrnFilter=${encodeURIComponent(mrnFilter)}`);
  });

  // GET: Search results latest page
  router.get('/mvp/v6/timeline/search-results-latest', (req, res) => {
    // Always prioritize query parameters - don't use session data for MRN/title
    const q = (req.query.q || '').trim();
    const mrnParam = (req.query.mrn || '').trim();
    // Only use session as fallback if no query params provided
    const sessionTitle = (!q && !mrnParam) ? (req.session.data?.title || '').trim() : '';
    // Use query parameter first, then session fallback, then default
    const title = q || mrnParam || sessionTitle || '25GBDD03IWJ3IHIAR1';
    const eventType = req.query.eventType || req.session.data?.eventType || 'all';
    const sortBy = req.query.sortBy || req.session.data?.sortBy || 'descending';
    
    req.session.data = req.session.data || {};
    // Always update session with current values to keep it in sync
    req.session.data.title = title;
    req.session.data.searchTerm = q || title;
    req.session.data.Cds = req.session.data.Cds || 'Customs declaration details';
    req.session.data.Ipaffs = req.session.data.Ipaffs || 'IPAFFS pre-notification (CHED) details';
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;

    res.render('mvp/v6/timeline/search-results-latest', {
      title,
      mrn: title,
      data: req.session.data
    });
  });

  // POST: Handle filter changes on search results latest page
  router.post('/mvp/v6/timeline/search-results-latest', (req, res) => {
    const eventType = req.body.eventType || 'all';
    const sortBy = req.body.sortBy || 'descending';
    const mrn = req.body.mrn || req.query.mrn || req.session.data?.title || '25GBC64QCLFMUHPAR2';

    req.session.data = req.session.data || {};
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;
    req.session.data.title = mrn;

    res.redirect(`/mvp/v6/timeline/search-results-latest?q=${encodeURIComponent(mrn)}&eventType=${eventType}&sortBy=${sortBy}`);
  });

  // GET: Search results cancel page
  router.get('/mvp/v6/timeline/search-results-cancel', (req, res) => {
    const q = (req.query.q || req.session.data?.searchTerm || '').trim();
    const mrnFilter = req.query.mrnFilter || req.session.data?.mrnFilter || '25GBCLNTWCC1FN7AR0';
    // Use mrnFilter as the primary title source, ignore session title from other pages
    const title = mrnFilter || (q ? q : '25GBCLNTWCC1FN7AR0');
    const eventType = req.query.eventType || req.session.data?.eventType || 'all';
    const sortBy = req.query.sortBy || req.session.data?.sortBy || 'descending';
    
    req.session.data = req.session.data || {};
    req.session.data.title = title;
    req.session.data.mrnFilter = mrnFilter;
    req.session.data.searchTerm = q || title;
    req.session.data.Cds = req.session.data.Cds || 'Customs declaration details';
    req.session.data.Ipaffs = req.session.data.Ipaffs || 'IPAFFS notification (CHED) details';
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;
    
    // Available MRNs for dropdown
    const availableMrns = [
      { value: '25GBCLNTWCC1FN7AR0', text: '25GBCLNTWCC1FN7AR0' },
      { value: '25GBBVWP03XACE8AR0', text: '25GBBVWP03XACE8AR0' }
    ];

    res.render('mvp/v6/timeline/search-results-cancel', {
      title,
      availableMrns,
      data: req.session.data
    });
  });

  // POST: Handle filter changes on search results cancel page
  router.post('/mvp/v6/timeline/search-results-cancel', (req, res) => {
    const eventType = req.body.eventType || 'all';
    const sortBy = req.body.sortBy || 'descending';
    const mrnFilter = req.body.mrnFilter || req.query.mrnFilter || req.session.data?.mrnFilter || '25GBCLNTWCC1FN7AR0';
    const mrn = req.body.mrn || req.query.mrn || mrnFilter;

    req.session.data = req.session.data || {};
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;
    req.session.data.mrnFilter = mrnFilter;
    req.session.data.title = mrnFilter;

    res.redirect(`/mvp/v6/timeline/search-results-cancel?mrnFilter=${encodeURIComponent(mrnFilter)}&eventType=${eventType}&sortBy=${sortBy}`);
  });

  // GET: GMR page
  router.get('/mvp/v6/timeline/gmr', (req, res) => {
    const gmr = req.query.gmr || req.session.data?.title || 'GMRA00002TT2';
    const q = (req.query.q || req.session.data?.searchTerm || gmr).trim();
    
    req.session.data = req.session.data || {};
    req.session.data.title = gmr;
    req.session.data.searchTerm = q;

    res.render('mvp/v6/timeline/gmr', {
      title: gmr,
      data: req.session.data
    });
  });
};
