// Generated by Cursor
// Routes for consignment timeline page

module.exports = (router) => {
  
  // Helper function to format dates for display (DD Month YYYY, HH:MM:SS)
  // Converts UTC dates to UK timezone for display
  function formatDateForDisplay(dateString) {
    try {
      const date = new Date(dateString);
      // Format in UK timezone using Intl.DateTimeFormat with seconds
      const formatter = new Intl.DateTimeFormat('en-GB', {
        timeZone: 'Europe/London',
        year: 'numeric',
        month: 'long',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: false
      });
      
      const parts = formatter.formatToParts(date);
      const day = parts.find(p => p.type === 'day').value;
      const month = parts.find(p => p.type === 'month').value;
      const year = parts.find(p => p.type === 'year').value;
      const hour = parts.find(p => p.type === 'hour').value;
      const minute = parts.find(p => p.type === 'minute').value;
      const second = parts.find(p => p.type === 'second').value;
      
      return `${day} ${month} ${year}, ${hour}:${minute}:${second}`;
    } catch (e) {
      return dateString;
    }
  }

  // Timeline events for MRN 25GBCLNTWCC1FN7ARO
  const MANUAL_RELEASE_TIMELINE_EVENTS = [
    {
      title: 'CDS finalisation',
      version: 1,
      cdsStatus: 'Finalised - Manually released',
      created: '2025-11-14T15:19:17Z',
      hasDetails: false
    },
    {
      title: 'BTMS decision',
      decision: '1',
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-11-14T11:47:28.433Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 2 - MISO PASTE</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 2103909089</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6769491</td>
              <td class="govuk-table__cell">H222</td>
              <td class="govuk-table__cell">POAO</td>
              <td class="govuk-table__cell">X00</td>
              <td class="govuk-table__cell">Incorrect CHED type</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CDS decision request',
      version: 1,
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-11-14T11:47:28.285Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 2 - MISO PASTE</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 2103909089</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6769491</td>
              <td class="govuk-table__cell">H222</td>
              <td class="govuk-table__cell">POAO</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CHEDD.GB.2025.6769491',
      chedStatus: 'Valid',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-11T15:35:35Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6769491',
      chedStatus: 'In progress',
      decision: 'Acceptable for Internal Market',
      created: '2025-10-29T15:46:31Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6769491',
      chedStatus: 'Submitted',
      decision: 'Acceptable for Internal Market',
      created: '2025-10-27T11:09:54Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6769491',
      chedStatus: 'Submitted',
      decision: 'Hold - Awaiting Decision',
      created: '2025-10-27T11:09:42Z',
      hasDetails: false
    }
  ];

  // Timeline events for MRN 25GBBVWP03XACE8ARO (Cancelled after arrival)
  const CANCELLED_TIMELINE_EVENTS = [
    {
      title: 'CDS finalisation',
      version: 1,
      cdsStatus: 'Finalised - Cancelled after arrival',
      created: '2025-11-14T11:44:07.762Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6769491',
      chedStatus: 'Valid',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-11T15:35:35Z',
      hasDetails: false
    },
    {
      title: 'BTMS decision',
      version: 2,
      decision: '2',
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-10-31T00:44:46.111Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 2 - MISO PASTE</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 2103909089</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6769491</td>
              <td class="govuk-table__cell">H222</td>
              <td class="govuk-table__cell">POAO</td>
              <td class="govuk-table__cell">X00</td>
              <td class="govuk-table__cell">Incorrect CHED type</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CDS decision request',
      version: 2,
      cdsStatus: 'In progress - Awaiting trader',
      created: '2025-10-31T00:44:45.996Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 2 - MISO PASTE</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 2103909089</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6769491</td>
              <td class="govuk-table__cell">H222</td>
              <td class="govuk-table__cell">POAO</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CHEDD.GB.2025.6769491',
      chedStatus: 'In progress',
      decision: 'Acceptable for Internal Market',
      created: '2025-10-29T15:46:31Z',
      hasDetails: false
    },
    {
      title: 'BTMS decision',
      version: 1,
      decision: 'Decision 1',
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-10-27T11:13:49.226Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 2 - MISO PASTE</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 2103909089</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6769491</td>
              <td class="govuk-table__cell">H222</td>
              <td class="govuk-table__cell">POAO</td>
              <td class="govuk-table__cell">X00</td>
              <td class="govuk-table__cell">Incorrect CHED type</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CDS decision request',
      version: 1,
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-10-27T11:13:49.113Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 2 - MISO PASTE</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 2103909089</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6769491</td>
              <td class="govuk-table__cell">H222</td>
              <td class="govuk-table__cell">POAO</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CHEDD.GB.2025.6769491',
      chedStatus: 'Submitted',
      decision: 'Acceptable for Internal Market',
      created: '2025-10-27T11:09:54Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6769491',
      chedStatus: 'Submitted',
      decision: 'Hold - Awaiting Decision',
      created: '2025-10-27T11:09:42Z',
      hasDetails: false
    }
  ];

  // Timeline events for MRN 25GBDD03IWJ3IHIAR1 (Latest page)
  const LATEST_TIMELINE_EVENTS = [
    {
      title: 'CDS decision request - processing error',
      version: 2,
      errorCode: 'ALVSVAL401',
      errorMessage: 'Error Description: The Entry Reference was not recognised. HMRC is unable to process the decision notification',
      created: '2025-12-04T19:07:47Z',
      hasDetails: false
    },
    {
      title: 'BTMS decision',
      decision: '2',
      cdsStatus: 'In progress - Awaiting CDS',
      created: '2025-12-04T19:07:46Z',
      hasDetails: true,
      detailsHtml: `
        <p class="govuk-body">Decision details for clearance decision 2</p>
      `
    },
    {
      title: 'CDS decision request',
      version: 2,
      created: '2025-12-04T19:07:46Z',
      hasDetails: true,
      detailsHtml: `
        <p class="govuk-body">Clearance request version 2 details</p>
      `
    },
    {
      title: 'CDS decision request - processing error',
      version: 2,
      errorCode: 'ALVSVAL401',
      errorMessage: 'EntryReference 25GBDD03IWJ3IHIAR1 EntryVersionNumber 2. This has already been replaced by a later version of the import declaration. Your request with correlation ID 2517565 has been terminated.',
      created: '2025-12-04T12:50:47Z',
      hasDetails: false
    },
    {
      title: 'BTMS decision',
      decision: '1',
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-12-03T15:00:29Z',
      hasDetails: true,
      detailsHtml: `
        <p class="govuk-body">Decision details for clearance decision 1</p>
      `
    },
    {
      title: 'CDS decision request',
      version: 1,
      created: '2025-12-03T15:00:29Z',
      hasDetails: true,
      detailsHtml: `
        <p class="govuk-body">Clearance request version 1 details</p>
      `
    },
    {
      title: 'CHEDPP.GB.2025.5627759',
      chedStatus: 'Valid',
      decision: 'Auto cleared',
      created: '2025-12-03T15:00:09Z',
      hasDetails: false
    },
    {
      title: 'CHEDPP.GB.2025.5627759',
      chedStatus: 'In progress',
      decision: 'Auto cleared',
      created: '2025-12-03T14:58:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDPP.GB.2025.5627759',
      chedStatus: 'Submitted',
      decision: 'Auto cleared',
      created: '2025-12-03T14:53:53Z',
      hasDetails: false
    },
    {
      title: 'CHEDPP.GB.2025.5627759',
      chedStatus: 'Submitted',
      decision: 'Auto cleared',
      created: '2025-12-03T14:53:52Z',
      hasDetails: false
    }
  ];

  // Custom timeline events for MRN 25GBC64QCLFMUHPAR2 (not shared)
  const CUSTOM_TIMELINE_EVENTS_25GBC64QCLFMUHPAR2 = [
    {
      title: 'CDS finalisation',
      version: 2,
      cdsStatus: 'Finalised - Released',
      created: '2025-11-06T09:24:20Z',
      hasDetails: false
    },
    {
      title: 'BTMS decision',
      decision: '6',
      cdsStatus: 'In progress - Awaiting CDS',
      created: '2025-11-06T09:13:48Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 1 - Sweet pepper</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709601000</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">C03</td>
              <td class="govuk-table__cell">Release - Inspection Complete</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">C03</td>
              <td class="govuk-table__cell">Release - Inspection Complete</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CDS decision request',
      version: 2,
      created: '2025-11-06T09:13:46Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 1 - Sweet pepper</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709601000</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CHEDPP.GB.2025.6801816',
      chedStatus: 'Valid',
      decision: 'Compliant',
      created: '2025-11-06T09:13:00Z',
      hasDetails: false
    }
  ];

  // Helper function to get timeline events based on MRN or page type
  // Add your timeline data constants here, then map them below
  function getTimelineEventsForMrn(mrn, pageType) {
    // Map MRNs to their specific timeline event arrays
    // You can add new MRNs and their corresponding event arrays here
    
    const timelineDataMap = {
      // Map specific MRNs to their timeline data
      '25GBBVWP03XACE8AR0': CANCELLED_TIMELINE_EVENTS,
      '25GBCLNTWCC1FN7AR0': MANUAL_RELEASE_TIMELINE_EVENTS,
      '25GBDD03IWJ3IHIAR1': LATEST_TIMELINE_EVENTS,
      '25GBC64QCLFMUHPAR2': CUSTOM_TIMELINE_EVENTS_25GBC64QCLFMUHPAR2,
      // Handle legacy variants with 'O' instead of '0'
      '25GBBVWP03XACE8ARO': CANCELLED_TIMELINE_EVENTS,
      '25GBCLNTWCC1FN7ARO': MANUAL_RELEASE_TIMELINE_EVENTS,
      '25GBDD03IWJ3IHIARO': LATEST_TIMELINE_EVENTS,
      '25GBC64QCLFMUHPARO': CUSTOM_TIMELINE_EVENTS_25GBC64QCLFMUHPAR2,
    };
    
    // First check for MRN-specific mapping
    if (timelineDataMap[mrn]) {
      return timelineDataMap[mrn];
    }
    
    // Then check for page-type-specific mapping
    if (timelineDataMap[pageType]) {
      return timelineDataMap[pageType];
    }
    
    // Default to empty array (data is now in search-results-timeline.html)
    return [];
  }

  // GET: Consignment timeline page
  router.get('/mvp/v5/timeline/consignment-timeline', (req, res) => {
    const mrn = req.query.mrn || '25GBC64QCLFMUHPAR2';
    const eventType = req.query.eventType || req.session.data?.eventType || 'all';
    // Always show newest to oldest (descending order)
    const sortBy = req.query.sortBy || req.session.data?.sortBy || 'descending';

    // Get timeline events specific to this MRN
    const eventsForThisMrn = getTimelineEventsForMrn(mrn, 'consignment-timeline');
    
    // Process timeline events using helper function with MRN-specific data
    const filteredEvents = processTimelineEvents(eventType, sortBy, eventsForThisMrn);

    res.render('mvp/v5/timeline/consignment-timeline', {
      mrn,
      timelineEvents: filteredEvents,
      data: {
        eventType,
        sortBy
      }
    });
  });

  // POST: Handle filter changes
  router.post('/mvp/v5/timeline/consignment-timeline', (req, res) => {
    const eventType = req.body.eventType || 'all';
    const sortBy = req.body.sortBy || 'descending';
    const mrn = req.body.mrn || req.query.mrn || '25GBCLNTWCC1FN7AR0';

    req.session.data = req.session.data || {};
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;

    res.redirect(`/mvp/v5/timeline/consignment-timeline?mrn=${encodeURIComponent(mrn)}&eventType=${eventType}&sortBy=${sortBy}`);
  });

  // Helper function to process timeline events (used by both routes)
  function processTimelineEvents(eventType, sortBy, eventsArray = null) {
    // Use provided events array or default to empty array (data is now in search-results-timeline.html)
    const sourceEvents = eventsArray || [];
    
    // Filter events by type
    let filteredEvents = sourceEvents;
    if (eventType !== 'all') {
      filteredEvents = sourceEvents.filter(event => {
        if (eventType === 'finalisation') return event.title === 'CDS finalisation';
        if (eventType === 'clearance-decision') return event.title === 'BTMS decision';
        if (eventType === 'clearance-request') return event.title === 'CDS decision request' || event.title === 'Error';
        if (eventType === 'ched' || eventType === 'ipaffs-pre-notification') return event.title.startsWith('CHED');
        return true;
      });
    }

    // Format dates and sort events by created time
    filteredEvents = filteredEvents.map(event => ({
      ...event,
      createdFormatted: formatDateForDisplay(event.created)
    }));

    // Always sort by created time (descending = newest first, ascending = oldest first)
    // Secondary sort by title to ensure consistent ordering when timestamps are identical
    filteredEvents.sort((a, b) => {
      const dateA = new Date(a.created).getTime();
      const dateB = new Date(b.created).getTime();
      
      // Primary sort by date
      if (dateA !== dateB) {
        return sortBy === 'ascending' ? dateA - dateB : dateB - dateA;
      }
      
      // Secondary sort by title for events with identical timestamps
      return a.title.localeCompare(b.title);
    });

    return filteredEvents;
  }

  // GET: Search results timeline page (now includes timeline data)
  router.get('/mvp/v5/timeline/search-results-timeline', (req, res) => {
    // Always prioritize query parameters - don't use session data for MRN/title
    const q = (req.query.q || '').trim();
    const mrnParam = (req.query.mrn || '').trim();
    const mrnFilterParam = (req.query.mrnFilter || '').trim();
    // Only use session as fallback if no query params provided
    const sessionTitle = (!q && !mrnParam && !mrnFilterParam) ? (req.session.data?.title || '').trim() : '';
    // Use query parameter first, then session fallback, then default
    const title = q || mrnParam || mrnFilterParam || sessionTitle || '25GBC64QCLFMUHPAR2';
    const eventType = req.query.eventType || req.session.data?.eventType || 'all';
    const sortBy = req.query.sortBy || req.session.data?.sortBy || 'descending';
    const mrnFilter = mrnFilterParam || title;
    
    req.session.data = req.session.data || {};
    // Always update session with current values to keep it in sync
    req.session.data.title = title;
    req.session.data.searchTerm = q || title;
    req.session.data.Cds = req.session.data.Cds || 'Customs declaration details';
    req.session.data.Ipaffs = req.session.data.Ipaffs || 'IPAFFS pre-notification (CHED) details';
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;
    req.session.data.mrnFilter = mrnFilter;

    // Sample list of MRNs (can be replaced with actual data source)
    const availableMrns = [title, '25GBC64QCLFMUHPAR2', '25GBC64QCLFMUHPAR3', '25GBC64QCLFMUHPAR4'];
    req.session.data.availableMrns = availableMrns;

    // Get timeline events specific to this MRN/page type
    const eventsForThisPage = getTimelineEventsForMrn(title, 'timeline');
    
    // Process timeline events with the specific data
    const timelineEvents = processTimelineEvents(eventType, sortBy, eventsForThisPage);

    res.render('mvp/v5/timeline/search-results-timeline', {
      title,
      mrn: title,
      timelineEvents,
      data: req.session.data
    });
  });

  // POST: Handle filter changes on search results page
  router.post('/mvp/v5/timeline/search-results-timeline', (req, res) => {
    const eventType = req.body.eventType || 'all';
    const sortBy = req.body.sortBy || 'descending';
    const mrnFilter = req.body.mrnFilter || req.query.mrnFilter || req.session.data?.title || '25GBC64QCLFMUHPAR2';
    const mrn = req.body.mrn || req.query.mrn || req.session.data?.title || '25GBC64QCLFMUHPAR2';

    req.session.data = req.session.data || {};
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;
    req.session.data.mrnFilter = mrnFilter;

    res.redirect(`/mvp/v5/timeline/search-results-timeline?q=${encodeURIComponent(mrnFilter)}&eventType=${eventType}&sortBy=${sortBy}&mrnFilter=${encodeURIComponent(mrnFilter)}`);
  });

  // GET: Search results latest page
  router.get('/mvp/v5/timeline/search-results-latest', (req, res) => {
    // Always prioritize query parameters - don't use session data for MRN/title
    const q = (req.query.q || '').trim();
    const mrnParam = (req.query.mrn || '').trim();
    // Only use session as fallback if no query params provided
    const sessionTitle = (!q && !mrnParam) ? (req.session.data?.title || '').trim() : '';
    // Use query parameter first, then session fallback, then default
    const title = q || mrnParam || sessionTitle || '25GBDD03IWJ3IHIAR1';
    const eventType = req.query.eventType || req.session.data?.eventType || 'all';
    const sortBy = req.query.sortBy || req.session.data?.sortBy || 'descending';
    
    req.session.data = req.session.data || {};
    // Always update session with current values to keep it in sync
    req.session.data.title = title;
    req.session.data.searchTerm = q || title;
    req.session.data.Cds = req.session.data.Cds || 'Customs declaration details';
    req.session.data.Ipaffs = req.session.data.Ipaffs || 'IPAFFS pre-notification (CHED) details';
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;

    // Get timeline events for the Latest tab - use the title (MRN) to look up correct data
    const eventsForThisPage = getTimelineEventsForMrn(title, 'latest');
    const timelineEvents = processTimelineEvents(eventType, sortBy, eventsForThisPage);

    res.render('mvp/v5/timeline/search-results-latest', {
      title,
      mrn: title,
      timelineEvents,
      data: req.session.data
    });
  });

  // POST: Handle filter changes on search results latest page
  router.post('/mvp/v5/timeline/search-results-latest', (req, res) => {
    const eventType = req.body.eventType || 'all';
    const sortBy = req.body.sortBy || 'descending';
    const mrn = req.body.mrn || req.query.mrn || req.session.data?.title || '25GBC64QCLFMUHPAR2';

    req.session.data = req.session.data || {};
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;
    req.session.data.title = mrn;

    res.redirect(`/mvp/v5/timeline/search-results-latest?q=${encodeURIComponent(mrn)}&eventType=${eventType}&sortBy=${sortBy}`);
  });

  // GET: Search results cancel page (based on image design)
  router.get('/mvp/v5/timeline/search-results-cancel', (req, res) => {
    const q = (req.query.q || req.session.data?.searchTerm || '').trim();
    const mrnFilter = req.query.mrnFilter || req.session.data?.mrnFilter || '25GBCLNTWCC1FN7AR0';
    // Use mrnFilter as the primary title source, ignore session title from other pages
    const title = mrnFilter || (q ? q : '25GBCLNTWCC1FN7AR0');
    const eventType = req.query.eventType || req.session.data?.eventType || 'all';
    const sortBy = req.query.sortBy || req.session.data?.sortBy || 'descending';
    
    req.session.data = req.session.data || {};
    req.session.data.title = title;
    req.session.data.mrnFilter = mrnFilter;
    req.session.data.searchTerm = q || title;
    req.session.data.Cds = req.session.data.Cds || 'Customs declaration details';
    req.session.data.Ipaffs = req.session.data.Ipaffs || 'IPAFFS notification (CHED) details';
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;

    // Get timeline events specific to this MRN/page type
    const eventsForThisPage = getTimelineEventsForMrn(title, 'cancel');
    
    // Process timeline events with the specific data
    const timelineEvents = processTimelineEvents(eventType, sortBy, eventsForThisPage);
    
    // Available MRNs for dropdown
    const availableMrns = [
      { value: '25GBCLNTWCC1FN7AR0', text: '25GBCLNTWCC1FN7AR0' },
      { value: '25GBBVWP03XACE8AR0', text: '25GBBVWP03XACE8AR0' }
    ];

    res.render('mvp/v5/timeline/search-results-cancel', {
      title,
      timelineEvents,
      availableMrns,
      data: req.session.data
    });
  });

  // POST: Handle filter changes on search results cancel page
  router.post('/mvp/v5/timeline/search-results-cancel', (req, res) => {
    const eventType = req.body.eventType || 'all';
    const sortBy = req.body.sortBy || 'descending';
    const mrnFilter = req.body.mrnFilter || req.query.mrnFilter || req.session.data?.mrnFilter || '25GBCLNTWCC1FN7AR0';
    const mrn = req.body.mrn || req.query.mrn || mrnFilter;

    req.session.data = req.session.data || {};
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;
    req.session.data.mrnFilter = mrnFilter;
    req.session.data.title = mrnFilter;

    res.redirect(`/mvp/v5/timeline/search-results-cancel?mrnFilter=${encodeURIComponent(mrnFilter)}&eventType=${eventType}&sortBy=${sortBy}`);
  });

  // GET: GMR page
  router.get('/mvp/v5/timeline/gmr', (req, res) => {
    const gmr = req.query.gmr || req.session.data?.title || 'GMRA00002TT2';
    const q = (req.query.q || req.session.data?.searchTerm || gmr).trim();
    
    req.session.data = req.session.data || {};
    req.session.data.title = gmr;
    req.session.data.searchTerm = q;

    res.render('mvp/v5/timeline/gmr', {
      title: gmr,
      data: req.session.data
    });
  });
};

