// Generated by Cursor
// Routes for consignment timeline page

module.exports = (router) => {
  
  // Helper function to format dates for display (DD Month YYYY, HH:MM)
  // Converts UTC dates to UK timezone for display
  function formatDateForDisplay(dateString) {
    try {
      const date = new Date(dateString);
      // Format in UK timezone using Intl.DateTimeFormat
      const formatter = new Intl.DateTimeFormat('en-GB', {
        timeZone: 'Europe/London',
        year: 'numeric',
        month: 'long',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
      });
      
      const parts = formatter.formatToParts(date);
      const day = parts.find(p => p.type === 'day').value;
      const month = parts.find(p => p.type === 'month').value;
      const year = parts.find(p => p.type === 'year').value;
      const hour = parts.find(p => p.type === 'hour').value;
      const minute = parts.find(p => p.type === 'minute').value;
      
      return `${day} ${month} ${year}, ${hour}:${minute}`;
    } catch (e) {
      return dateString;
    }
  }

  // Sample timeline events matching the screen design
  const SAMPLE_TIMELINE_EVENTS = [
    {
      title: 'Finalisation',
      version: 2,
      cdsStatus: 'Finalised - Released',
      created: '2025-11-06T09:24:00Z',
      hasDetails: false
    },
    {
      title: 'Clearance decision',
      decision: '6',
      cdsStatus: 'In progress - CDS',
      created: '2025-11-06T09:13:00Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 1 - Sweet pepper</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 1601009999</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 4 - Pomegranate</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0810907530</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6803042</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 5 - Table grapes</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0806101090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 7 - Chilli peppers</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709609920</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 8 - Pears</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0808309090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 9 - Corn</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709996090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 10 - Egg plant</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 14 - Carrot</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 15 - Raddish</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CHEDPP GB 2025.6801816',
      chedStatus: 'Valid',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-06T09:15:00Z',
      hasDetails: false
    },
    {
      title: 'Clearance decision',
      decision: '5',
      cdsStatus: 'In progress - Awaiting IPAFFS',

      created: '2025-11-05T19:09:00Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 1 - Sweet pepper</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 1601009999</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 4 - Pomegranate</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0810907530</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6803042</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 5 - Table grapes</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0806101090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 7 - Chilli peppers</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709609920</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 8 - Pears</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0808309090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 9 - Corn</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709996090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 10 - Egg plant</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 14 - Carrot</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 15 - Raddish</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'Clearance request',
      version: 2,
      created: '2025-11-05T19:09:00Z',
      hasDetails: true,
      detailsHtml: '<p>Additional details about this clearance request would appear here.</p>'
    },
    {
      title: 'Clearance decision',
      decision: '4',
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-11-03T17:16:00Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 1 - Sweet pepper</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 1601009999</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 4 - Pomegranate</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0810907530</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6803042</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 5 - Table grapes</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0806101090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 7 - Chilli peppers</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709609920</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 8 - Pears</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0808309090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 9 - Corn</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709996090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 10 - Egg plant</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 14 - Carrot</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 15 - Raddish</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CHEDD.GB.2025.6803042',
      chedStatus: 'Valid',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-03T18:35:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6802963',
      chedStatus: 'In progress',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-03T18:10:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6803042',
      chedStatus: 'Valid',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-03T18:05:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6803042',
      chedStatus: 'In progress',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-03T17:59:00Z',
      hasDetails: false
    },
    {
      title: 'Clearance decision',
      decision: '2',
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-09-03T15:17:00Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 1 - Sweet pepper</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 1601009999</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 4 - Pomegranate</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0810907530</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6803042</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 5 - Table grapes</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0806101090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 7 - Chilli peppers</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709609920</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 8 - Pears</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0808309090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 9 - Corn</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709996090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 10 - Egg plant</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 14 - Carrot</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 15 - Raddish</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'Clearance decision',
      decision: '3',
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-09-03T17:05:00Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 1 - Sweet pepper</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 1601009999</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 4 - Pomegranate</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0810907530</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6803042</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 5 - Table grapes</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0806101090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 7 - Chilli peppers</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709609920</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 8 - Pears</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0808309090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 9 - Corn</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709996090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 10 - Egg plant</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 14 - Carrot</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 15 - Raddish</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CHEDD.GB.2025.6802999',
      chedStatus: 'Valid',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-03T15:17:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6802999',
      chedStatus: 'In progress',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-03T15:09:00Z',
      hasDetails: false
    },
    {
      title: 'Clearance decision',
      decision: '1',
      cdsStatus: 'In progress - Awaiting IPAFFS',
      created: '2025-09-03T14:56:00Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 1 - Sweet pepper</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 1601009999</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 4 - Pomegranate</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0810907530</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6803042</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 5 - Table grapes</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0806101090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 7 - Chilli peppers</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709609920</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
              <td class="govuk-table__cell">H01</td>
              <td class="govuk-table__cell">Hold - Awaiting decision</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 8 - Pears</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0808309090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 9 - Corn</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709996090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 10 - Egg plant</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 14 - Carrot</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-m govuk-!-margin-top-4">Item 15 - Raddish</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
              <th scope="col" class="govuk-table__header">Decision code</th>
              <th scope="col" class="govuk-table__header">Decision</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
              <td class="govuk-table__cell">H02</td>
              <td class="govuk-table__cell">Hold - To be inspected</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'Clearance request',
      version: 1,
      created: '2025-11-03T14:56:00Z',
      hasDetails: true,
      detailsHtml: `
        <h3 class="govuk-heading-m govuk-!-margin-top-0">Item 1 - Sweet pepper</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 1601009999</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-s govuk-!-margin-top-4">Item 4 - Pomegranate</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0810907530</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6803042</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-s govuk-!-margin-top-4">Item 5 - Table grapes</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0806101090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-s govuk-!-margin-top-4">Item 7 - Chilli peppers</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709609920</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6802963</td>
              <td class="govuk-table__cell">H223</td>
              <td class="govuk-table__cell">FNAO</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-s govuk-!-margin-top-4">Item 8 - Pears</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0808309090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H218</td>
              <td class="govuk-table__cell">HMI-SMS</td>
            </tr>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-s govuk-!-margin-top-4">Item 9 - Corn</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709996090</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-s govuk-!-margin-top-4">Item 10 - Egg plant</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-s govuk-!-margin-top-4">Item 14 - Carrot</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
            </tr>
          </tbody>
        </table>
        <h3 class="govuk-heading-s govuk-!-margin-top-4">Item 15 - Raddish</h3>
        <p class="commodity-code"><strong>Commodity code:</strong> 0709300005</p>
        <table class="govuk-table">
          <thead class="govuk-table__head">
            <tr class="govuk-table__row">
              <th scope="col" class="govuk-table__header">CHED reference</th>
              <th scope="col" class="govuk-table__header">Check code</th>
              <th scope="col" class="govuk-table__header">Authority</th>
            </tr>
          </thead>
          <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
              <td class="govuk-table__cell">GBCHD2025.6801816</td>
              <td class="govuk-table__cell">H219</td>
              <td class="govuk-table__cell">PHSI</td>
            </tr>
          </tbody>
        </table>
      `
    },
    {
      title: 'CHEDD.GB.2025.6801816',
      chedStatus: 'In progress',
      decision: 'Hold - Awaiting Decision',
      created: '2025-11-03T14:52:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6803042',
      chedStatus: 'Submitted',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-03T14:43:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6803042',
      chedStatus: 'Submitted',
      decision: 'Hold - Awaiting Decision',
      created: '2025-11-03T14:43:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6802999',
      chedStatus: 'Submitted',
      decision: 'Hold - Awaiting Decision',
      created: '2025-11-03T14:40:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6802963',
      chedStatus: 'Submitted',
      decision: 'Acceptable for Internal Market',
      created: '2025-11-03T14:37:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDD.GB.2025.6802963',
      chedStatus: 'Submitted',
      decision: 'Hold - Awaiting Decision',
      created: '2025-11-03T14:37:00Z',
      hasDetails: false
    },
    {
      title: 'CHEDPP GB 2025.6801816',
      chedStatus: 'Submitted',
      decision: 'Hold - Awaiting Decision',
      created: '2025-11-03T12:28:00Z',
      hasDetails: false
    }
  ];

  // GET: Consignment timeline page
  router.get('/mvp/v5/consignment-timeline', (req, res) => {
    const mrn = req.query.mrn || '25GBC64QCLFMUHPAR2';
    const eventType = req.query.eventType || req.session.data?.eventType || 'all';
    const sortBy = req.query.sortBy || req.session.data?.sortBy || 'descending';

    // Filter events by type
    let filteredEvents = SAMPLE_TIMELINE_EVENTS;
    if (eventType !== 'all') {
      filteredEvents = SAMPLE_TIMELINE_EVENTS.filter(event => {
        if (eventType === 'finalisation') return event.title === 'Finalisation';
        if (eventType === 'clearance-decision') return event.title === 'Clearance decision';
        if (eventType === 'clearance-request') return event.title === 'Clearance request';
        if (eventType === 'ched' || eventType === 'ipaffs-pre-notification') return event.title.startsWith('CHED');
        return true;
      });
    }

    // Format dates and sort events by created time
    filteredEvents = filteredEvents.map(event => ({
      ...event,
      createdFormatted: formatDateForDisplay(event.created)
    }));

    // Always sort by created time (descending = newest first, ascending = oldest first)
    filteredEvents.sort((a, b) => {
      const dateA = new Date(a.created).getTime();
      const dateB = new Date(b.created).getTime();
      return sortBy === 'ascending' ? dateA - dateB : dateB - dateA;
    });

    res.render('mvp/v5/timeline/consignment-timeline', {
      mrn,
      timelineEvents: filteredEvents,
      data: {
        eventType,
        sortBy
      }
    });
  });

  // POST: Handle filter changes
  router.post('/mvp/v5/consignment-timeline', (req, res) => {
    const eventType = req.body.eventType || 'all';
    const sortBy = req.body.sortBy || 'descending';
    const mrn = req.body.mrn || req.query.mrn || '25GBC64QCLFMUHPAR2';

    req.session.data = req.session.data || {};
    req.session.data.eventType = eventType;
    req.session.data.sortBy = sortBy;

    res.redirect(`/mvp/v5/consignment-timeline?mrn=${encodeURIComponent(mrn)}&eventType=${eventType}&sortBy=${sortBy}`);
  });

  // GET: Search results timeline page
  router.get('/mvp/v5/timeline/search-results-timeline', (req, res) => {
    const q = (req.query.q || req.session.data?.searchTerm || '').trim();
    const sessionTitle = (req.session.data?.title || '').trim();
    const title = sessionTitle || (q ? q : '25GBC64QCLFMUHPAR2');
    
    req.session.data = req.session.data || {};
    req.session.data.title = title;
    req.session.data.searchTerm = q || title;
    req.session.data.Cds = req.session.data.Cds || 'Customs declaration details';
    req.session.data.Ipaffs = req.session.data.Ipaffs || 'IPAFFS pre-notification (CHED) details';

    res.render('mvp/v5/timeline/search-results-timeline', {
      title,
      data: req.session.data
    });
  });
};

